Repository linea-it/dri, pull requests merged in 2020-12, with the labels that each got.

#1267 Target Cutout and Integration with DESaccess
  api/common/views.py
  api/dri/settings/defaults.py
  api/product/descutoutservice.py
  api/product/models.py
  api/product/serializers.py
  api/product/tasks.py
  api/product/views.py
  frontend/target/app/Application.js
  frontend/target/app/model/Cutout.js
  frontend/target/app/model/CutoutJob.js
  frontend/target/app/store/CutoutJobs.js
  frontend/target/app/store/Cutouts.js
  frontend/target/app/view/objects/CutoutJobDetailWindow.js
  frontend/target/app/view/objects/Mosaic.js
  frontend/target/app/view/objects/ObjectsController.js
  frontend/target/app/view/objects/ObjectsModel.js
  frontend/target/app/view/objects/Panel.js
  frontend/target/app/view/settings/CutoutJobController.js
  frontend/target/app/view/settings/CutoutJobForm.js
  frontend/target/app/view/settings/CutoutJobModel.js
Labels: Feature

#1269 Download Target List compatible with DESacces.
  api/product/descutoutservice.py
  api/product/export.py
  api/product/tasks.py
  frontend/target/app/view/objects/DownloadWindow.js
Labels: Targets, enhancement

#1259 Fixing contrast bug and removing features from tile inspection
  api/dri/settings/local_vars.py.template
  frontend/eyeballing/package.json
  frontend/eyeballing/public/index.html
  frontend/eyeballing/src/api/Api.js
  frontend/eyeballing/src/components/Counter.js
  frontend/eyeballing/src/components/SearchField.js
  frontend/eyeballing/src/components/TileTable.js
  frontend/eyeballing/src/components/visiomatic/Visiomatic.js
  frontend/eyeballing/src/home.js
  frontend/landing_page/src/pages/Home/partials/Interfaces/index.js
Labels: Feature

#1273 Sky Viewer UI improvements
  frontend/packages/local/aladin/src/Aladin.js
  frontend/packages/local/aladin/src/Events.js
  frontend/packages/local/aladin/src/Interface.js
  frontend/packages/local/visiomatic/sass/src/Visiomatic.scss
  frontend/packages/local/visiomatic/src/Visiomatic.js
  frontend/sky/app/view/dataset/Dataset.js
  frontend/sky/app/view/dataset/DatasetController.js
  frontend/sky/app/view/footprint/Aladin.js
Labels: enhancement

#1274 Target Viwer UI improvements
  api/product/views.py
  frontend/packages/local/common/src/header/Toolbar.js
  frontend/target/app/store/CatalogsTree.js
  frontend/target/app/view/catalog/Tree.js
  frontend/target/app/view/objects/Panel.js
  frontend/target/app/view/preview/Preview.js
  frontend/target/app/view/preview/PreviewController.js
Labels: enhancement

#1279 Improve Target List Registry form
  api/common/views.py
  api/dri/urls.py
  api/product/views.py
  frontend/landing_page/src/Services/api.js
  frontend/landing_page/src/components/Banner/styles.js
  frontend/landing_page/src/components/Header/index.js
  frontend/landing_page/src/pages/Home/partials/Interfaces/styles.js
  frontend/landing_page/src/pages/Home/partials/Supporters/styles.js
  frontend/packages/local/aladin/src/Aladin.js
  frontend/packages/local/aladin/src/Events.js
  frontend/packages/local/aladin/src/Interface.js
  frontend/packages/local/common/src/header/Toolbar.js
  frontend/packages/local/visiomatic/sass/src/Visiomatic.scss
  frontend/packages/local/visiomatic/src/Visiomatic.js
  frontend/sky/app/view/dataset/Dataset.js
  frontend/sky/app/view/dataset/DatasetController.js
  frontend/sky/app/view/footprint/Aladin.js
  frontend/target/app/store/CatalogsTree.js
  frontend/target/app/view/catalog/CSVForm.js
  frontend/target/app/view/catalog/DatabaseController.js
  frontend/target/app/view/catalog/DatabaseForm.js
  frontend/target/app/view/catalog/Tree.js
  frontend/target/app/view/objects/Panel.js
  frontend/target/app/view/preview/Preview.js
  frontend/target/app/view/preview/PreviewController.js
Labels: enhancement

#1281 Fixed error when ordering a list of targets in Oracle
  api/lib/CatalogDB.py
Labels: Targets, bug
