Repository linea-it/dri, pull requests merged in 2021-01, with the labels that each got.

#1309 Feat/tile download
  api/coadd/views.py
  frontend/eyeballing/public/visiomatic/visiomatic/dist/images/icon-download.svg
  frontend/eyeballing/public/visiomatic/visiomatic/dist/visiomatic-src.js
  frontend/eyeballing/public/visiomatic/visiomatic/dist/visiomatic.css
  frontend/eyeballing/src/api/Api.js
  frontend/eyeballing/src/components/download/index.js
  frontend/eyeballing/src/components/visiomatic/Visiomatic.js
  frontend/eyeballing/src/home.js
  frontend/packages/local/visiomatic/sass/src/Visiomatic.scss
  frontend/packages/local/visiomatic/src/Visiomatic.js
  frontend/packages/local/visiomatic/src/download/DescutDownloadWindow.js
  frontend/packages/local/visiomatic/src/download/FitsController.js
  frontend/packages/local/visiomatic/src/download/FitsModel.js
  frontend/packages/local/visiomatic/src/model/FitsFiles.js
  frontend/packages/local/visiomatic/src/store/FitsFiles.js
  frontend/packages/local/visiomatic/src/visiomatic/dist/images/icon-download.svg
  frontend/packages/local/visiomatic/src/visiomatic/dist/visiomatic-src.js
  frontend/packages/local/visiomatic/src/visiomatic/dist/visiomatic.css
  frontend/sky/app/view/dataset/Dataset.js
  frontend/sky/app/view/dataset/DatasetController.js
  frontend/target/app/view/objects/ObjectsController.js
  frontend/target/app/view/preview/Preview.js
  frontend/target/app/view/preview/PreviewController.js
  frontend/userquery/app/view/main/Main.js
Labels: Feature

#1311 Target Viewer Upload CSV file
  api/product/views.py
  frontend/nginx-proxy-develop.conf
  frontend/nginx-proxy.conf
  frontend/target/app/view/catalog/CSVController.js
  frontend/target/app/view/catalog/CSVForm.js
  frontend/target/app/view/catalog/CatalogController.js
  frontend/target/app/view/catalog/RegisterWindow.js
  frontend/target/app/view/catalog/Tree.js
Labels: Feature, Targets Viewer

#1316 Fixed Overlay DR2 Public
  Docs/exemplo_importacao_coadd_object_dr2_public.json
  api/catalog/views.py
  api/product/association.py
Labels: Django, bug

#1319 Fixed Cutout register images
  api/product/descutoutservice.py
Labels: Targets Viewer, bug

#1320 Query by position using Q3c
  api/lib/CatalogDB.py
  api/lib/db_oracle.py
  api/lib/db_postgresql.py
Labels: Feature, Python
